### PR TITLE
feat(docker): added a dockerfile and made a small readme markdown file

### PR DESCRIPTION
**Pull request by goldsziggy**
awesome work on this!

I have to break out my guns again and give this a go.  I thought having the server dockerized might help with barrier to entry, and help people stand up some servers.

Also create a README.md to get some better formatting

### CODE REVIEW

**Comment by aarushbothra** [comment]
Great idea! I'm new to docker, so quick question: Does docker auto-update?

**Comment by goldsziggy** [comment]
By itself no, but we can create a github action workflow to auto build and publish on tags (or commits it’s up to you).  If you want some help with it let me know!

**Comment by aarushbothra** [comment]
Hmm. Its a good call to make it easier for people to be able to run an update the server on their machines, but adding a docker would prevent a lot of people from running the server on Windows if they wanted to, as the docker windows application only works on professional and enterprise windows. I'll take a hint from you and make a better formatted readme though!

**Comment by aarushbothra** [comment]
I appreciate your interest though!

**Comment by goldsziggy** [comment]
No problem!  Do you have a backlog of features you are looking to add for server or app?  I can probably assist on some spare time

**Comment by aarushbothra** [comment]
I do, but I want to understand your skills a little more:
1. Do you know how to work JSON in python?
2. Do you have the tools/skills to work with Android or iOS?
3. Do you have anything you want to add to the app?

**Comment by goldsziggy** [comment]
1. I've done some JSON in python for a work hackathon on machine learning.

2. Yeah I have a MacBook Pro so I can do either, it's been a bit for native app dev but I've built one for each

3. Haven't done to much in yet, could probably use some UX work, although admittedly I'm better at implementing UX then designing it

**Comment by aarushbothra** [comment]
Honestly, you've got more skills than me! We'll utilize them in the future. 

For now, read the server protocol documentation to get some understanding of that. I'll write up some documentation on things we still have to do.

**Comment by aarushbothra** [comment]
https://docs.google.com/document/d/16goEr0JouGlq-TjOW4kZiPXpNWD1Jbu_dvwQn-9cVXI/edit?usp=sharing

Here's the doc of stuff I want to get done. Lmk if you are willing to take any of them on!!

**Pull request closed without merging**
